from .voices import (
    DIALECT_MAPPINGS,
    DEFAULT_DIALECT_MAPPING,
    QWEN_TTS_LANGUAGE_MAP,
    COSYVOICE_DEFAULT_VOICE_ID,
    OMNIVOICE_GENDER_MAP,
    OMNIVOICE_AGE_MAP,
    OMNIVOICE_DIALECT_MAP,
    OMNIVOICE_INSTRUCT_GENDER,
    OMNIVOICE_INSTRUCT_AGE,
)

__all__ = [
    "DIALECT_MAPPINGS",
    "DEFAULT_DIALECT_MAPPING",
    "QWEN_TTS_LANGUAGE_MAP",
    "COSYVOICE_DEFAULT_VOICE_ID",
    "OMNIVOICE_GENDER_MAP",
    "OMNIVOICE_AGE_MAP",
    "OMNIVOICE_DIALECT_MAP",
    "OMNIVOICE_INSTRUCT_GENDER",
    "OMNIVOICE_INSTRUCT_AGE",
]
