#!/usr/bin/env bash
# new-bug.sh — bug-hunt 7 字段 bug 单生成脚本（V11.8.2 NEW Stage 6 Phase A；V11.9 扩展 --source）
#
# 用法: bash scripts/bug-hunt/new-bug.sh BUG-017 M4-asset /zh/workspace/asset-hub L2 "evidence" [--source qa-found|user-feedback|scan]
# 产物: docs/bugs/<YYYY-MM-DD>/<bug_id>-<module_slug>.md
#
# 反 V11-BH3 反例: 16 个 bug 单每单 1 min 手填 = 16 min 浪费。本脚本替代手填。
#
# 占位符:
#   {bug_id}    - 必填, 格式 BUG-NNN 或 BUG-YYYY-MM-DD-NNN
#   {module}    - 必填, 格式 M{N}-{name}
#   {route}     - 必填, / 开头
#   {severity}  - 必填, L1 / L2 / L3 / L4
#   {evidence}  - 必填, 简短描述
#   {source}    - 可选, --source 传参, 默认 qa-found; 值 ∈ qa-found | user-feedback | scan（bug 单第 7 字段, role-protocol §6）

set -euo pipefail

# 解析可选 --source 标志（允许出现在任意位置；其余按位置参数收集）
SOURCE="qa-found"
POSITIONAL=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --source)
            if [[ $# -lt 2 ]]; then
                echo "[FATAL] --source 缺少取值（qa-found | user-feedback | scan）" >&2
                exit 1
            fi
            SOURCE="$2"
            shift 2
            ;;
        *)
            POSITIONAL+=("$1")
            shift
            ;;
    esac
done
set -- "${POSITIONAL[@]}"

if [[ $# -lt 4 ]]; then
    echo "[FATAL] 用法: bash $0 <bug_id> <module> <route> <severity> [\"evidence\"] [--source qa-found|user-feedback|scan]" >&2
    echo "  示例: bash $0 BUG-017 M4-asset /zh/workspace/asset-hub L2 \"playwright 404\"" >&2
    echo "  示例: bash $0 BUG-018 M4-asset /api/list L1 \"用户反馈 500\" --source user-feedback" >&2
    exit 1
fi

BUG_ID="$1"
MODULE="$2"
ROUTE="$3"
SEVERITY="$4"
EVIDENCE="${5:-（待补 — 主代理补 Description + Fix）}"

# 校验
case "$SEVERITY" in
    L1|L2|L3|L4) ;;
    *) echo "[FATAL] severity 必为 L1/L2/L3/L4, 收到: $SEVERITY" >&2; exit 1 ;;
esac

case "$SOURCE" in
    qa-found|user-feedback|scan) ;;
    *) echo "[FATAL] source 必为 qa-found/user-feedback/scan, 收到: $SOURCE" >&2; exit 1 ;;
esac

if [[ ! "$ROUTE" =~ ^/ ]]; then
    echo "[FATAL] route 必以 / 开头, 收到: $ROUTE" >&2; exit 1
fi

# 模块名 → slug
MODULE_SLUG=$(echo "$MODULE" | tr '[:upper:]' '[:lower:]')

# 当前日期（TZ=Asia/Shanghai）
OBSERVED_AT=$(TZ=Asia/Shanghai date +"%Y-%m-%dT%H:%M:%S+08:00")
DATE_DIR=$(TZ=Asia/Shanghai date +"%Y-%m-%d")

# 输出路径
OUT_DIR="docs/bugs/${DATE_DIR}"
OUT_FILE="${OUT_DIR}/${BUG_ID}-${MODULE_SLUG}.md"

mkdir -p "$OUT_DIR"

# 校验不覆盖已存在
if [[ -f "$OUT_FILE" ]]; then
    echo "[FATAL] bug 单已存在, 不覆盖: $OUT_FILE" >&2
    exit 1
fi

# 写模板（generated by new-bug.sh 标记供 test 反向校验）
cat > "$OUT_FILE" <<EOF
<!-- generated by new-bug.sh at ${OBSERVED_AT} -->

# ${BUG_ID} — ${MODULE_SLUG}

> **V11 Stage 6 Bug Fix & Hunt Phase A** 录入模板（auto-generated by new-bug.sh）。
>
> 主代理 Phase A Step 3 落单后**必补 Description + Fix 段**。
>
> 产物路径: \`${OUT_FILE}\`

---

## 7 字段（V11 §8 + role-protocol §6 source）

| 字段 | 值 |
|------|-----|
| bug_id | ${BUG_ID} |
| module | ${MODULE} |
| observed_at | ${OBSERVED_AT} |
| route | ${ROUTE} |
| evidence | ${EVIDENCE} |
| severity | ${SEVERITY} |
| source | ${SOURCE} |
| status | OPEN |
| blocked_by | （人工填 — 关联上游 bug / spec / commit hash） |

## Severity 定义（V11 §0 §3.7）

| 等级 | 定义 | 修复 wave |
|------|------|----------|
| **L1** | 阻断：页面不可达 / 全页崩溃 / 控制台 fatal error / hydration mismatch | 当 wave 必修 |
| **L2** | 局部不可用：关键 CTA 无响应 / 数据 401 / route 不存在 / API 鉴权失败 | 当 wave 修 |
| **L3** | 视觉走样：缺 CSS 变量 / 字体降级 / 布局塌缩 / i18n key 未翻译 / 主题色错位 | 批 wave 修 |
| **L4** | 体验瑕疵：mock 占位 / 文案瑕疵 / 对齐偏差 / 错误提示不友好 | 可选 wave 修 |

## Status 状态机（V11 §3）

| 状态 | 含义 | 转换条件 |
|------|------|----------|
| **OPEN** | 已落单，待修复 | 主代理 Phase A 落单 |
| **IN-FIX** | 修复中 | 子代理实施中（V11 Stage 6 Phase B Step 6）|
| **FIXED** | 已修复，待验证 | 子代理实施完成（V11 Stage 6 Phase B Step 7 验收通过）|
| **VERIFIED** | 已验证，再观察一轮无 regression | 主代理再跑 4 维度观察 |
| **REOPENED** | 复测失败回退，待重修 | 测试专家复测 FIXED 失败（role-protocol §6）|
| **OBSOLETE** | 功能变更致过时（终态） | 仅测试专家可标（role-protocol §6）|
| **CLOSED** | 关闭，归档到 done/ | 状态机终态（V11 Article VIII 不可变）|

> **必备转换约束**：
> - OPEN → IN-FIX：必须先填 Description（期望/实际/复现/环境 + visible_text + console_logs + screenshot 归档路径）
> - IN-FIX → FIXED：必须先填 Fix（修复策略 + 关联 code:line + 关联 spec + 影响面 + 回归测试）
> - FIXED → VERIFIED：必须再跑一轮 4 维度观察无 regression
> - VERIFIED → CLOSED：归档到 \`docs/bugs/archive/done/${BUG_ID}/\`

## Description（主代理 Phase A 落单后必填）

<!-- TODO: 主代理补充 visible_text 关键句 + console_logs 摘要 + 截图归档路径 -->

## Fix（Phase B Step 6 修复后由 sub-agent 填）

<!-- TODO: sub-agent 补充修复策略 + file:line + 关联 spec + 回归测试 -->

## 关联引用

- Stage 6 SKILL.md: ../SKILL.md
- Phase A 流程: ../references/bug-hunt-phase-a.md
- 4 维度观察法: ../references/bug-hunt-4d-observation.md
- 5 项证据抽检: ../references/bug-hunt-5-check.md
- 实战报告: ../references/bug-hunt-battle-report.md
- close-bug.sh: ./close-bug.sh
- 同模块其他 bug: \`docs/bugs/index.md\`
EOF

echo "[OK] ${BUG_ID} → ${OUT_FILE}（generated by new-bug.sh）"